### ISSUE TITLE
[FEATURE] Back to Top Button

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [KiranAminPanjwani/MedStats#1]
### 🎇 Description

- I would like to create a back to top arrow button for the website.
- Responsive for any type of devices.
- Hovering with neon light effect.
- Best user experience with smooth scroll functioning.
- Helpful for the user to reach out to the top of the website in one click.

### 🖼 Screenshots

![image](https://github.com/KiranAminPanjwani/MedStats/assets/114330097/c23884fd-20a6-4fc1-b3cc-3e5e97d6cd34)

- No back to top button.

**Comment by Avdhesh-Varshney** [comment]
@KiranAminPanjwani please assign this task to me to contribute under hacktoberfest 2023

**Comment by KiranAminPanjwani** [comment]
> @KiranAminPanjwani please assign this task to me to contribute under hacktoberfest 2023

Please go ahead☺️.

**Comment by JatinBawne** [comment]
@KiranAminPanjwani Kindly assign this issue to me, will fix this in no time.

**Comment by arpy8** [comment]
Please assign this task to me
