### ISSUE TITLE
Data Add in Record

### ISSUE THREAD

**Issue by Dhruvrode** [KiranAminPanjwani/MedStats#10]
### 🎇 Description

Hey @KiranAminPanjwani  there are some errors in index.html i can try to solve that.

New Feature:
 Can add a feature in journal entry. When we click on add Your record now the data will be showed here .

### 🖼 Screenshots

![image](https://github.com/KiranAminPanjwani/MedStats/assets/89011471/bfedc422-ef6f-4aed-9e2d-427a3bfb61b3)

**Comment by Dhruvrode** [comment]
Hey @KiranAminPanjwani  please assign me this i would love to contribute :) !

**Comment by KiranAminPanjwani** [comment]
Please proceed.😇

**Comment by Dhruvrode** [comment]
Thank you so much :)

**Comment by Dhruvrode** [comment]
Hello @KiranAminPanjwani,

I have submitted a pull request for the mentioned issue. Kindly consider adding the label "hacktober-accepted" if you find my work satisfactory. You can find the pull request under issue  #17  .

Please let me know if my changes meet your requirements or if there are any mistakes that need to be addressed.

Thank you for providing me with the opportunity to contribute to this repository!
