### ISSUE TITLE
Use of icons in consistent format and style

### ISSUE THREAD

**Issue by mdtausifiqbal** [KiranAminPanjwani/MedStats#104]
### 🎇 Description

we can use font awesome icons across all pages rather than using svg or png of icons from different sources. this will enhance the UI of the website

### 🖼 Screenshots

![image](https://github.com/KiranAminPanjwani/MedStats/assets/33699526/958b381d-0c70-4d49-849b-f0d14900c134)

**Comment by mdtausifiqbal** [comment]
@KiranAminPanjwani please assign me this issue

**Comment by avdhendra** [comment]
can i work on this issue

**Comment by mdtausifiqbal** [comment]
@avdhendra already I am working on.
