### ISSUE TITLE
Edit Record Would containt Patient name

### ISSUE THREAD

**Issue by bhupendraKhatri12** [KiranAminPanjwani/MedStats#106]
### 🎇 Description

when we edit the record input would add patient label  i have fixed it 

### 🖼 Screenshots

![image](https://github.com/KiranAminPanjwani/MedStats/assets/45266621/41f9aab1-75c3-4b5f-aabd-52e2bbfc1f37)

**Comment by bhupendraKhatri12** [comment]
Please assigned it to me i have fixed it

**Comment by KiranAminPanjwani** [comment]
Sure, please proceed.✨

**Comment by Aryan1982** [comment]
@KiranAminPanjwani  it was already mentioned by me in #97 and has been fixed in #110.

**Comment by KiranAminPanjwani** [comment]
@bhupendraKhatri12 I believe you can still work on the 'patient' input field. The record shouldn't require users to input their patient's name. Logically, when a user logs into MedStats, they intend to track their health record. The person logging in with their own name indicates that the record pertains to them exclusively. Therefore, I find the 'Patient' input field unnecessary. After logging in, the user's name should be displayed in the top right corner of the page, inside the navbar.
