### ISSUE TITLE
[FEATURE] Adding Glassmorphism to the navbar.

### ISSUE THREAD

**Issue by NateNear** [KiranAminPanjwani/MedStats#109]
### 🎇 Description

Adding glassmorphism to the navbar may improve user experience.

### 🖼 Screenshots

Something like this.

![image](https://github.com/KiranAminPanjwani/MedStats/assets/92938055/474f14d6-020c-46f7-b9b4-803c44b7e993)

**Comment by KiranAminPanjwani** [comment]
Could you please explain how adding glassmorphism to the navbar will enhance the user experience?

**Comment by NateNear** [comment]
Provides better visuals to the user

**Comment by KiranAminPanjwani** [comment]
> Provides better visuals to the user

But we are following a light theme. How will you implement it?

**Comment by KiranAminPanjwani** [comment]
We aim to use a simple and elegant theme that aligns with MedStats. If you believe that implementing your design would enhance the UI in a more decent, responsive, minimalistic, yet impressive manner, please proceed.
