### ISSUE TITLE
Some of the sections of site are not responsive in mobile phone

### ISSUE THREAD

**Issue by rutikgagare** [KiranAminPanjwani/MedStats#11]
### 🎇 Description

Symptoms medication section is not responsive in the mobile phone I can style it and make it responsive for all type of devices.

### 🖼 Screenshots

![Screenshot_720](https://github.com/KiranAminPanjwani/MedStats/assets/85502114/34722a1c-d457-4f24-a10e-b1918b6af108)

**Comment by KiranAminPanjwani** [comment]
Sure, please proceed.😇

**Comment by KiranAminPanjwani** [comment]
Hey, 
Are you working on it?
