### ISSUE TITLE
[FEATURE] Storing data in local storage

### ISSUE THREAD

**Issue by sunnydaysinseoul** [KiranAminPanjwani/MedStats#114]
### 🎇 Description

Hi, I saw you closed the Issue #83 of implementing MongoDB, but I would want to suggest adding a local storage property to store data. It will still stay with Vanilla Javasciprt and I think having multiple records saved in your browser will make the development eaiser for making things like grid layout, moving cards by drag and drop... or maybe connecting records to the progress bar.

Well then, I'll have to edit script.js.

Let me know and assign me if it's ok.

Thank you 😄

**Comment by KiranAminPanjwani** [comment]
Sure, please go ahead.✨

**Comment by sunnydaysinseoul** [comment]
Updated the pull request! Waiting for the review 😄
