### ISSUE TITLE
[FEATURE] report card enhancement 

### ISSUE THREAD

**Issue by Aryan1982** [KiranAminPanjwani/MedStats#117]
### 🎇 Description

The card could look more clean with good spacing of buttons, inputs and icons

![image](https://github.com/KiranAminPanjwani/MedStats/assets/62349184/92f98b67-1ac2-479b-bfe5-17611c5a6672)

**Comment by ShreyasSaunshi** [comment]
!assign

**Comment by mdtausifiqbal** [comment]
@KiranAminPanjwani please assign me
