### ISSUE TITLE
[FEATURE] Insted of alert messages, we can create our own modals that shows the error or success

### ISSUE THREAD

**Issue by Aryan1982** [KiranAminPanjwani/MedStats#118]
### 🎇 Description

 Insted of using alert messages, we can create our own modals that shows the error or message

![image](https://github.com/KiranAminPanjwani/MedStats/assets/62349184/c1b2080c-5911-4de3-af2c-55b936e0d19c)

similar to #116 
with just 'ok' button

**Comment by CrownPab** [comment]
Hello, may I be assigned this issue for Hacktoberfest?

**Comment by KiranAminPanjwani** [comment]
> Hello, may I be assigned this issue for Hacktoberfest?

Please visit #66
