### ISSUE TITLE
[FEATURE] User Account Profiles

### ISSUE THREAD

**Issue by CrownPab** [KiranAminPanjwani/MedStats#121]
### 🎇 Description

I would like to implement an SQLite database to the project to store user profiles and add the functionality for the sign up and login page. 

### 🖼 Screenshots

<img width="1680" alt="Screenshot 2023-10-17 at 16 51 45" src="https://github.com/KiranAminPanjwani/MedStats/assets/35786720/511cebee-e7e5-469a-a373-0c92b1b91061">

**Comment by KiranAminPanjwani** [comment]
Thank you so much for suggesting this. But, I would not like to proceed with with this issue. The purpose of this repository was to assist beginners who have recently entered the development and open-source world. Adding SQLite database to the project will pose difficulties for front-end (HTML/CSS/JS) users and limit their ability to contribute. Therefore, I'm closing this one.
