### ISSUE TITLE
Footer Glitch in Login Page

### ISSUE THREAD

**Issue by pranavsuriya-sr** [KiranAminPanjwani/MedStats#131]
### 🎇 Description

The footer in the login page isn't properly designed. The footer should like the one in the home page. 
Please assign this issue to me.

### 🖼 Screenshots

How it is now...
![image](https://github.com/KiranAminPanjwani/MedStats/assets/91081814/947b65c1-7ce0-4c37-ba26-dd2df3f0901e)
How it should be....
![image](https://github.com/KiranAminPanjwani/MedStats/assets/91081814/1310d82d-4876-4e90-9efe-bb23292ddbb9)

**Comment by KiranAminPanjwani** [comment]
Sure, please go ahead✨

**Comment by pranavsuriya-sr** [comment]
Closing as it has been completed.

**Comment by KiranAminPanjwani** [comment]
> Closing as it has been completed.

Please check out Issue #66
