### ISSUE TITLE
[Enhancement] The cursor should become pointer while hovering the 'Check Your Progress' checkpoints

### ISSUE THREAD

**Issue by JatinBawne** [KiranAminPanjwani/MedStats#14]
### 🎇 Description

While hovering to the checkpoints under the 'Check You Progress' the cursor should change to POINTER to enhance the user experience.

### 🖼 Screenshots

https://github.com/KiranAminPanjwani/MedStats/assets/99788083/6e9e628f-202c-44f2-9eab-45941b23b9b6

**Comment by JatinBawne** [comment]
Its done, kindly check it once, assign it to me and merge my PR.

https://github.com/KiranAminPanjwani/MedStats/assets/99788083/5e38e66f-fb55-41b7-9b5a-367d6b54cae5

**Comment by KiranAminPanjwani** [comment]
The provided clip is not functioning; I'm unable to view it. If applicable, please submit a pull request along with screenshots in JPG format.

**Comment by JatinBawne** [comment]
@KiranAminPanjwani kindly review

Uploading FILE 2023-10-11 10:48:13.mp4…

**Comment by JatinBawne** [comment]
<img width="1273" alt="Screenshot 2023-10-11 at 10 48 55 AM" src="https://github.com/KiranAminPanjwani/MedStats/assets/99788083/06a50087-856f-4266-b070-cfadd312147b">
