### ISSUE TITLE
[FEATURE] Styling the vertical scroll bar

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [KiranAminPanjwani/MedStats#20]
### 🎇 Description

- Styling the vertical scroll bar of the website.
- Glassmorphism effect
- Attractive look
- Follow the same colour code of the website
- Very interactive for the users.

**Comment by Avdhesh-Varshney** [comment]
@KiranAminPanjwani please assign this task to me to contribute under hacktoberfest 2023

**Comment by KiranAminPanjwani** [comment]
Sure, please proceed 😇

**Comment by kunal-511** [comment]
I would be happy to contribute.Please assign me this task

**Comment by KiranAminPanjwani** [comment]
@Avdhesh-Varshney is working on it.
