### ISSUE TITLE
Accessibility Issues on Form 

### ISSUE THREAD

**Issue by marisabrantley** [KiranAminPanjwani/MedStats#23]
### 🎇 Description

There seems to be issues with the form labels and corresponding form input code.

Per WAVE (Web Accessibility Evaluation Tool), the form labels are not correctly associated with a form control, so that a screen reader will not be able to convey that the form label is connected to the form input text area.

Please assign this to me with the Hacktoberfest label.

### 🖼 Screenshots

<img width="1266" alt="Screen Shot 2023-10-10 at 8 09 52 PM" src="https://github.com/KiranAminPanjwani/MedStats/assets/60168324/b361119f-1df3-4978-b0e2-683a7643b83a">

**Comment by KiranAminPanjwani** [comment]
Sure, please proceed.😇 But ensure that you incorporate the theme colors into your design.
