### ISSUE TITLE
[FEATURE] Creating Navbar for good user experience

### ISSUE THREAD

**Issue by JatinBawne** [KiranAminPanjwani/MedStats#26]
### 🎇 Description

As of now, no buttons/hyperlinks are there in Navbar like 'About', 'Contact Us', 'Login' , etc.

we can add some of those with a minimal hover animation to enhance user experience.

### 🖼 Screenshots

<img width="1440" alt="Screenshot 2023-10-11 at 12 52 20 PM" src="https://github.com/KiranAminPanjwani/MedStats/assets/99788083/ffa9bb00-8c02-4f75-9055-5acaa4ce431a">

**Comment by JatinBawne** [comment]
@KiranAminPanjwani kindly assign this issue to me.

**Comment by KiranAminPanjwani** [comment]
Sure, please proceed 😇

**Comment by JatinBawne** [comment]
<img width="1439" alt="Screenshot 2023-10-11 at 4 29 24 PM" src="https://github.com/KiranAminPanjwani/MedStats/assets/99788083/3ad1290c-4b54-4a27-8480-1aad4ecdf2e9">

**Comment by JatinBawne** [comment]
@KiranAminPanjwani issue has been resolved. kindly review and merge
