### ISSUE TITLE
[FEATURE] Login screen

### ISSUE THREAD

**Issue by Mldamico** [KiranAminPanjwani/MedStats#3]
### 🎇 Description

I want to build a login screen. Also adding a button in the home page in order to navigate.

**Comment by KiranAminPanjwani** [comment]
Please go ahead☺️, but ensure that you incorporate the theme colors into your design.

**Comment by Kallind** [comment]
can i work on this?

**Comment by KiranAminPanjwani** [comment]
Sure

**Comment by riyanrathore26** [comment]
I want to work on it 
please assign me this issue

**Comment by KiranAminPanjwani** [comment]
> I want to work on it please assign me this issue

There is room for many other issues in this project. I would appreciate it if you could highlight a new one in this repository.

**Comment by riyanrathore26** [comment]
so are you saying that this issue is fixed?

**Comment by KiranAminPanjwani** [comment]
> so are you saying that this issue is fixed?

@Kallind is working on it.
