### ISSUE TITLE
In the footer section, the copyright year should be dynamically generated instead of being statically hardcoded.

### ISSUE THREAD

**Issue by gauravsingh1281** [KiranAminPanjwani/MedStats#33]
### 🎇 Description

@KiranAminPanjwani Right now, the copyright year is written manually, which means someone has to change it whenever a new year begins. However, with just a few lines of code in JavaScript, we can make it automatic. This means that the copyright year will always be up-to-date without anyone having to change it manually. For example, if the current year is 2023, the copyright section will show 2023. And when the year changes to 2024, the copyright section will automatically update to 2024.

### 🖼 Screenshots

<img width="959" alt="Screenshot 2023-10-11 232652" src="https://github.com/KiranAminPanjwani/MedStats/assets/85905403/39130c06-f801-4cd6-b667-4389f9dca1d0">

**Comment by gauravsingh1281** [comment]
@KiranAminPanjwani  Please assign this issue to me under hacktoberfest label.

**Comment by KiranAminPanjwani** [comment]
Sure, please proceed 😇

**Comment by MrDBC** [comment]
@KiranAminPanjwani 
i can solve it right away.

**Comment by gauravsingh1281** [comment]
Hii @KiranAminPanjwani I will do this today actually I was busy with my College exam. Now I'm free.

**Comment by KiranAminPanjwani** [comment]
> Hii @KiranAminPanjwani I will do this today actually I was busy with my College exam. Now I'm free.

Since the issue has been resolved by @MrDBC, could you please report another issue? Alternatively, you can enhance the footer using your creativity or by adding any necessary elements to it.
