### ISSUE TITLE
Refactor Home UI

### ISSUE THREAD

**Issue by dipanshparmar** [KiranAminPanjwani/MedStats#35]
### 🎇 Description

I feel there is room for UI improvements on the home page. I would like to update the UI and make it more accessible.

**Comment by dipanshparmar** [comment]
@KiranAminPanjwani Can you please assign this to me?

**Comment by dipanshparmar** [comment]
Nevermind. Just noticed that there is another issue active for the same thing

**Comment by KiranAminPanjwani** [comment]
> Nevermind. Just noticed that there is another issue active for the same thing

Hey, my apologies for the delayed response. You are absolutely welcome to proceed; there is ample room for numerous improvements in this repository. If we focus on the UI, you have the opportunity to showcase your creativity. Alternatively, you can visit the Readme.md, where you will find a list of additional options to contribute, including some of the features that need to be added to this repository

**Comment by dipanshparmar** [comment]
Sure! I'll just wait for @imsp18 to do his magic on #16. If I feel that I can add something on top of that, I'll reopen this. Meanwhile, I'll look into [README.md](https://github.com/KiranAminPanjwani/MedStats/blob/main/Readme.md).
