### ISSUE TITLE
Code Refactor

### ISSUE THREAD

**Issue by dipanshparmar** [KiranAminPanjwani/MedStats#36]
### 🎇 Description

Right now, all the JS code is inside the `index.html` file. I feel that the JS code should be in its separate file and then should be linked in the HTML file. Not a big issue, but can be considered for making the code more maintainable.

**Comment by dipanshparmar** [comment]
@KiranAminPanjwani may you please assign this to me?

**Comment by KiranAminPanjwani** [comment]
Please proceed ✨
