### ISSUE TITLE
changed ui of login box and footer sticked to bottom

### ISSUE THREAD

**Issue by Ishaa11** [KiranAminPanjwani/MedStats#46]
### 🎇 Description

Changed the ui of existing Login page and sticked the footer to the bottom as it was coming in middle

### 🖼 Screenshots

![Screenshot (25)](https://github.com/KiranAminPanjwani/MedStats/assets/64044485/3f89a715-b831-4b83-b4a5-35c4f4e3acb8)
![Screenshot (26)](https://github.com/KiranAminPanjwani/MedStats/assets/64044485/d2af83c9-36b0-49cc-b003-da34388d74e0)

**Comment by Ishaa11** [comment]
hey im not able to push the commit have you denied acces s?

**Comment by KiranAminPanjwani** [comment]
No, I haven't changed any settings

**Comment by Ishaa11** [comment]
remote: Permission to KiranAminPanjwani/MedStats.git denied to Ishaa11.
fatal: unable to access 'https://github.com/KiranAminPanjwani/MedStats.git/': The requested URL returned error: 403 this is what im getting

**Comment by KiranAminPanjwani** [comment]
Wait, let me check this

**Comment by Ishaa11** [comment]
sure

**Comment by KiranAminPanjwani** [comment]
![Discord](https://img.shields.io/badge/@kiran__6018-%235865F2.svg?style=for-the-badge&logo=discord&logoColor=white)

**Comment by Ishaa11** [comment]
I've sent you new PR and new Issue please check that , this one had some error due to my system. Thanks!
