### ISSUE TITLE
Logo icon in Log-Out page is different & Home button

### ISSUE THREAD

**Issue by JatinBawne** [KiranAminPanjwani/MedStats#58]
### 🎇 Description

Logo icon in log-out page is different from the original logo and also there should be a button in log-out's page navbar to navigate to the HOME PAGE.

**LOGO IN HOME PAGE**
<img width="1440" alt="Screenshot 2023-10-13 at 9 57 01 PM" src="https://github.com/KiranAminPanjwani/MedStats/assets/99788083/4bec01ce-d83f-46d3-8868-f0b75e2a751e">

**LOGO IN LOGOUT PAGE**
<img width="1438" alt="Screenshot 2023-10-13 at 9 57 25 PM" src="https://github.com/KiranAminPanjwani/MedStats/assets/99788083/3e3beef2-5979-426b-aced-661f13283b45">

**Comment by JatinBawne** [comment]
@KiranAminPanjwani kindly assign this issue to me.

**Comment by KiranAminPanjwani** [comment]
What kind of button?

**Comment by KiranAminPanjwani** [comment]
> @KiranAminPanjwani kindly assign this issue to me.

Sure, please proceed 🙌

**Comment by JatinBawne** [comment]
<img width="1440" alt="Screenshot 2023-10-13 at 10 13 32 PM" src="https://github.com/KiranAminPanjwani/MedStats/assets/99788083/5977f06c-415c-440d-8017-aa4da55e8fe5">

@KiranAminPanjwani  kindly review and merge
