### ISSUE TITLE
Adding signup page 

### ISSUE THREAD

**Issue by Akan45** [KiranAminPanjwani/MedStats#61]
### 🎇 Description

Adding signup page and doing necessary changes in login page also adding logo to login page and correct some silly mistakes in navbar.

Thankyou.

.

**Comment by KiranAminPanjwani** [comment]
An issue for improving the logo on the login page is already active. Visit #58 
However, you can proceed with adding a signup page to MedStats

**Comment by 22Yash** [comment]
can I work on these?

**Comment by Akan45** [comment]
@KiranAminPanjwani  Okay Mam.

**Comment by KiranAminPanjwani** [comment]
> can I work on these?

@Akan45 is working on it. Please report another issue.
