### ISSUE TITLE
Add Dark mode for Website

### ISSUE THREAD

**Issue by rishirohilla** [KiranAminPanjwani/MedStats#63]
### 🎇 Description

Adding a dark and light mode option for Website inside Navbar

**Comment by rishirohilla** [comment]
Kindly assign me this issue @KiranAminPanjwani

**Comment by uttkarsh1m** [comment]
hey @KiranAminPanjwani kindly assign me the issue

**Comment by KiranAminPanjwani** [comment]
> ### 🎇 Description
> Adding a dark and light mode option for Website inside Navbar
> 
> ### 🖼 Screenshots
> _No response_

Sure, please proceed ✨

**Comment by 22Yash** [comment]
can i also work on these?

**Comment by riyanrathore26** [comment]
I want to work on this 
please assign me this issue

**Comment by riyanrathore26** [comment]
I want to work on this issue
please assign me this issue

**Comment by KiranAminPanjwani** [comment]
> I want to work on this issue please assign me this issue

You are already assigned.

**Comment by KiranAminPanjwani** [comment]
@22Yash @riyanrathore26 Please visit #66

**Comment by KiranAminPanjwani** [comment]
@rutikgagare Any updates?

**Comment by rishirohilla** [comment]
hey @KiranAminPanjwani  you may assign it to @uttkarsh1m

**Comment by KiranAminPanjwani** [comment]
Okay
