### ISSUE TITLE
Copyright and resposiveness

### ISSUE THREAD

**Issue by manish-bhukar** [KiranAminPanjwani/MedStats#68]
We can add a copyright at footer with year changes dynamically and page collapse for small screen so we can fix that issue also.
<img width="341" alt="image" src="https://github.com/KiranAminPanjwani/MedStats/assets/125037273/8aec7e19-6d8c-4aa4-89f5-6f34dac96e67">

**Comment by MrDBC** [comment]
refer to my fix #70 for the dynamic copyright year change
