### ISSUE TITLE
Adding footer

### ISSUE THREAD

**Issue by shreyamaurya029** [KiranAminPanjwani/MedStats#71]
### 🎇 Description

feature is to add footer at the end of the website, currently website doesn't have one

**Comment by MrDBC** [comment]
![image](https://github.com/KiranAminPanjwani/MedStats/assets/69349350/a04dc929-e8a6-489d-8eb8-a5d1c4dcdaa5)

actually there is footer, but its not visible due to linking wrong classes in css
i have fixed that already in this PR #70

**Comment by shreyamaurya029** [comment]
ok, i'll close this issue. thank you !!
