### ISSUE TITLE
[FEATURE] Navbar items hovering can be improved

### ISSUE THREAD

**Issue by youtanimstar** [KiranAminPanjwani/MedStats#75]
### 🎇 Description

@KiranAminPanjwani When we hover over the navbar items, the hovering effect is not optimal. I believe this effect can be improved. Therefore, please assign this task to me

### 🖼 Screenshots

![Screenshot from 2023-10-14 17-49-13](https://github.com/KiranAminPanjwani/MedStats/assets/107903218/0a63d685-2c84-490a-8271-8cbaecff24ae)

**Comment by DhairyaMajmudar** [comment]
@KiranAminPanjwani ma'am pls. assign me the issue

**Comment by KiranAminPanjwani** [comment]
Sure, please proceed @youtanimstar

**Comment by KiranAminPanjwani** [comment]
> @KiranAminPanjwani ma'am pls. assign me the issue

Please visit #66

**Comment by youtanimstar** [comment]
> Sure, please proceed @youtanimstar

Thank you for assigning this task to me. I will do my best. 😊
