### ISSUE TITLE
[FEATURE] Make a popup to show data when user cilck a node in progress bar

### ISSUE THREAD

**Issue by karitthorn** [KiranAminPanjwani/MedStats#76]
### Make popup when users click a node in progress bar .It will show 

- [ ] - the date when the user's health condition was categorized 
- [ ] - The specific health status, such as healthy, poor, improved, or fair.

You can assign this to me .Thanks you✨

**Comment by KiranAminPanjwani** [comment]
Sure, please proceed.✨

**Comment by karitthorn** [comment]
![Screenshot 2566-10-15 at 11 12 43](https://github.com/KiranAminPanjwani/MedStats/assets/56643494/adf04672-15c5-468d-a900-5eee288530a1)

How do you think with this popup👍

**Comment by KiranAminPanjwani** [comment]
> ![Screenshot 2566-10-15 at 11 12 43](https://user-images.githubusercontent.com/56643494/275300892-adf04672-15c5-468d-a900-5eee288530a1.png)
> 
> How do you think with this popup👍

That's awesome! However, please ensure that instead of adding random text, you display the symptoms and medications added by the user when recording.
