### ISSUE TITLE
REFACTOR PROJECT TO USE REACT

### ISSUE THREAD

**Issue by koyaboy** [KiranAminPanjwani/MedStats#82]
### 🎇 Description

I went through some of the intended functionality of the system and I believe refactoring the code to use a framework like React will make life easier in the long run.

It will mean faster development and more efficiency.

Just a suggestion

**Comment by KiranAminPanjwani** [comment]
Sure, please go ahead! 🙌✨ However, it's important to keep your forked repository in sync regularly since contributions are coming in frequently. Additionally, new functionalities are continually being added to existing features, so please manage accordingly.

**Comment by mdtausifiqbal** [comment]
@koyaboy I am also working on this issue, converting this repo into Next.js (React Framework) project so that all UI, theme and pages are consistent style.

**Comment by KiranAminPanjwani** [comment]
Okay, so I think we should not proceed with this issue. The purpose of this repository was to assist beginners who have recently entered the development and open-source world. Changing the framework of the project will pose difficulties for HTML/CSS/JS users and limit their ability to contribute. Therefore, I'm closing this one.
