### ISSUE TITLE
[FEATURE] <Backend Functionality>

### ISSUE THREAD

**Issue by koyaboy** [KiranAminPanjwani/MedStats#83]
### 🎇 Description

Currently, when a patient's name is added along with symptoms and medications, it disappears on refresh.

If you are intending to make this a full-stack app such that the information will be saved on a database, I can help with this using MongoDB. I'm very familiar with the MERN stack and capable of doing this.

If this is your wish, let us talk further

**Comment by KiranAminPanjwani** [comment]
@koyaboy  Let's keep this issue on hold for the time being. Allow people to finish adding some of the functionalities, and then we can move forward with it. What are your thoughts on this approach?

**Comment by koyaboy** [comment]
@KiranAminPanjwani that makes sense but I see the issue as closed so is this something you don't want to move forward with anymore ?

**Comment by KiranAminPanjwani** [comment]
> @KiranAminPanjwani that makes sense but I see the issue as closed so is this something you don't want to move forward with anymore ?

Yes, I think we should not proceed with this issue. The purpose of this repository was to assist beginners who have recently entered the development and open-source world. Adding the Backend using MongoDB will pose difficulties for front-end (HTML/CSS/JS) users and limit their ability to contribute. Therefore, I'm closing this one.
