### ISSUE TITLE
[FEATURE] Update Contact Us page to be more consistent with the styling

### ISSUE THREAD

**Issue by n4itik** [KiranAminPanjwani/MedStats#87]
### 🎇 Description

- Change the `form-img` to one with similar color palette as the rest of the UI
- Have the same border radii across all the input fields
- Restrict resizing of the text area
- Change button color for improved contrast

### 🖼 Screenshots

Before:

![image](https://github.com/KiranAminPanjwani/MedStats/assets/66974007/b04129a4-2100-4f3c-9fe2-a554447348a8)

After:

![image](https://github.com/KiranAminPanjwani/MedStats/assets/66974007/6deb7a6c-aabb-47d8-b301-8d20401ff52c)

**Comment by Aryan1982** [comment]
I have fixed this in #86, is that alright?

**Comment by n4itik** [comment]
PR #88 includes the fixes. Please review. Thanks!
