### ISSUE TITLE
Save button appears without any functionality

### ISSUE THREAD

**Issue by Aryan1982** [KiranAminPanjwani/MedStats#92]
### 🎇 Description

The save button should only appear while editing the record

### 🖼 Screenshots

![image](https://github.com/KiranAminPanjwani/MedStats/assets/62349184/f4c2959c-99c8-46b5-9667-10a80de519d3)
Currently the save button is appearing immediately after adding new record.

**Comment by Aryan1982** [comment]
Please assign me this issue , I can fix this.

**Comment by KiranAminPanjwani** [comment]
Good highlight! Sure, please go ahead.✨
