### ISSUE TITLE
[FEATURE] UI Improvement 

### ISSUE THREAD

**Issue by bhupendraKhatri12** [KiranAminPanjwani/MedStats#96]
### 🎇 Description

As This ui looks basic i have designed the UI 

### 🖼 Screenshots

![image](https://github.com/KiranAminPanjwani/MedStats/assets/45266621/5e115711-864a-4706-91bb-7886dcac689d)

**Comment by KiranAminPanjwani** [comment]
Awesome, this looks good, but let's improve the logo part. Add the white 'MedStats' text in PNG format for the logo. Additionally, while the color theme is good, the current colors are too vibrant for users. They don't align with the theme. Let's go for more subtle, decent colors that are still impressive.

**Comment by bhupendraKhatri12** [comment]
i have changed the logo to be transparent white

**Comment by bhupendraKhatri12** [comment]
Please check and close this
