### ISSUE TITLE
Prevent user to save empty values while editing

### ISSUE THREAD

**Issue by Aryan1982** [KiranAminPanjwani/MedStats#97]
### 🎇 Description

Users can keep records empty while editing a record

I will be happy to contribute to this issue

### 🖼 Screenshots

![image](https://github.com/KiranAminPanjwani/MedStats/assets/62349184/ad47ab6a-ee15-4c33-b1d4-415deaa76458)

![image](https://github.com/KiranAminPanjwani/MedStats/assets/62349184/01b23523-521f-4fb5-bff0-5513ec5cfa0a)

**Comment by Aryan1982** [comment]
One more thing 
the "Patient : " should be outside of the input field and cannot be edited

 ![image](https://github.com/KiranAminPanjwani/MedStats/assets/62349184/8bad1bef-7b87-46ed-a014-92fc6720786e)

**Comment by KiranAminPanjwani** [comment]
Please incorporate #99 into this one, as it pertains to the same issue. Once the bugs are resolved, kindly submit a reference to this one, as I'll be closing #99.
